### ISSUE TITLE
Starting the script under Windows

### ISSUE THREAD

**Issue by joergoster** [vondele/nevergrad4sf#1]
Under Windows, one must invoke the script with _mpiexec_.
```
mpiexec -np 4 hostname
DESKTOP-K096CVK
DESKTOP-K096CVK
DESKTOP-K096CVK
DESKTOP-K096CVK
```

This works:

> mpiexec -np 2 python -m mpi4py.futures nevergrad4sf.py --cutechess cutechess-cli.exe --stockfish stockfish.exe -tc 2+0.02 -g 40 -cc 3 -ec 1 --ng 4

**Comment by vondele** [comment]
OK that's a documentation issue, and depends on the version of mpi one has installed, both commands are commonly used, mpiexec seems the standard one:
https://stackoverflow.com/questions/25287981/mpiexec-vs-mpirun
